"""add is_approved to users

Revision ID: 14b03ef9443e
Revises: f10c500510dc
Create Date: 2026-07-23 23:11:15.635084

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14b03ef9443e"
down_revision: Union[str, Sequence[str], None] = "f10c500510dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_approved", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_approved")
    # ### end Alembic commands ###
