"""add cascade delete and indexes

Revision ID: f10c500510dc
Revises: 9d07940c6a68
Create Date: 2026-06-27 16:46:13.550050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10c500510dc'
down_revision: Union[str, Sequence[str], None] = '9d07940c6a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_service_request_id'), 'comments', ['service_request_id'], unique=False)
    op.drop_constraint(op.f('comments_service_request_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_author_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'service_requests', ['service_request_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_service_line_items_service_request_id'), 'service_line_items', ['service_request_id'], unique=False)
    op.drop_constraint(op.f('service_line_items_service_request_id_fkey'), 'service_line_items', type_='foreignkey')
    op.create_foreign_key(None, 'service_line_items', 'service_requests', ['service_request_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_requests_mechanic_id'), 'service_requests', ['mechanic_id'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_vehicle_id'), 'service_requests', ['vehicle_id'], unique=False)
    op.drop_constraint(op.f('service_requests_mechanic_id_fkey'), 'service_requests', type_='foreignkey')
    op.drop_constraint(op.f('service_requests_customer_id_fkey'), 'service_requests', type_='foreignkey')
    op.create_foreign_key(None, 'service_requests', 'users', ['mechanic_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'service_requests', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
    op.drop_constraint(op.f('vehicles_customer_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_customer_id_fkey'), 'vehicles', 'users', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.create_foreign_key(op.f('service_requests_customer_id_fkey'), 'service_requests', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('service_requests_mechanic_id_fkey'), 'service_requests', 'users', ['mechanic_id'], ['id'])
    op.drop_index(op.f('ix_service_requests_vehicle_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_mechanic_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_constraint(None, 'service_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('service_line_items_service_request_id_fkey'), 'service_line_items', 'service_requests', ['service_request_id'], ['id'])
    op.drop_index(op.f('ix_service_line_items_service_request_id'), table_name='service_line_items')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('comments_service_request_id_fkey'), 'comments', 'service_requests', ['service_request_id'], ['id'])
    op.drop_index(op.f('ix_comments_service_request_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    # ### end Alembic commands ###
